### ISSUE TITLE
About the hyperedge convolution module

### ISSUE THREAD

**Issue by ooCher** [iMoonLab/DHGNN#1]
I have read your code for a long time, but I don't know which part is the code about the hyperedge convolution module. Wish you a good day!

**Comment by weiyx15** [comment]
Thank you for your feedback! The hyperedge convolution is not a necessary part of this framework and the module can be found in `MultiClusterConvolution` in `models/layers.py`, where `x = self.self_attention(x)` serves as the hyperedge convolution module. Hope this reply can help you! Best wishes!
