### ISSUE TITLE
About the DHGNN model

### ISSUE THREAD

**Issue by HaiyuZhou** [iMoonLab/DHGNN#2]
I was wondering where is the code for DHGNN model, maybe you forget releasing the part of this. I only found the HGNN model, and still don't know the type of `G` in `models/model.py`  line821,  it seems not like the egde_dict in other models like DynamicGCN, could you add some annotation about this.
Best wishes!

**Comment by weiyx15** [comment]
We apologize for our delayed reply. I struggled with projects and exams recently.  I have cleared up and updated the codes. Now you can find DHGNN as the class defined at  line:8 in `models/models.py`. Wish this could help you!
Best Wishes!
