### ISSUE TITLE
关于随机划分cora数据集

### ISSUE THREAD

**Issue by CigaLi** [iMoonLab/DHGNN#3]
您好，
代码中关于任意划分cora数据集的函数是cora.py中的load_cora_data(cfg, add_self_path=True)函数，其中idx_features_labels = np.genfromtxt(cfg['cora_ft'], dtype=np.dtype(str))一行中的cfg['cora_ft']参数是什么意思，在config_cora.yaml文件中并未见到，希望能指点一下，非常感谢。

**Comment by weiyx15** [comment]
您好！
非常抱歉，前段时间忙于期末考试和项目，这么晚才回复您。我们使用原始cora数据集进行切分，您指的`cora_ft`字段是原始数据集的路径（原始cora数据参见论文`McCallum, A., Nigam, K., Rennie, J., & Seymore, K. (2000). Automating the construction of internet portals with machine learning. Information Retrieval, 3, 127- 163.`）。至于随机切分, 还需要额外对training set进行sample. 希望以上回复能对您有帮助！
祝好！
